.PHONY: clean help

help:
	@echo "           Targets"
	@echo "         clean - clean auxiliary and output files"
	@echo "          help - show this message and exit"

# Remove LaTeX auxiliary files
clean:
		rm -f *.app *.aux *.bbl *.blg *.bcf *.synctex*
		rm -f *.fdb_latexmk *.fls *.gz
		rm -f *.lof *.log *.lol *.lot *.out *.status
		rm -f *.toc *.xml *-blx.bib *.pdf

